### ISSUE TITLE
What's the difference between this plugin and my script?

### ISSUE THREAD

**Issue by alexkubica** [qaware/go-offline-maven-plugin#17]
Hey man, I love your plugin.
3 years ago I came up with [this script](https://gist.github.com/ak-il/6bf7e3bdb807c2c247434911aab0778a) to download maven artifacts and their dependencies for offline work.
Your plugin greatly simplified the progress and I updated the gist to use it instead.
However I noticed there is a difference in the downloaded files' size.
My script gets much more files and I wonder what's the difference?
Also would it be possible to have the plugin work as a CLI without needing a POM file?
I'd like to have a way to pass a text file as an argument that lists the artifacts I want to download like my script can.
Many thanks!

**Comment by Theoderich** [comment]
Hi,
Looking over the script I would guess the plugin does a few things differently:
- Go-Offline also downloads plugin dependencies (but the script could be modified to do that)
- Your script most likely fails when used on a reactor-project with internal interdependencies and an empty repository (that is the main reason I built the plugin)
- your scripts main usecase seems to be "download a specific artifact with dependencies". My plugins main usecase is "download everything I need to build my local project

I would be very interested to test the differences in downloaded artifacts between my plugin and your script. Can you provide me with an example pom/artifactId with which the difference occurs?

It is certainly possible to add a goal to the plugin that works without a pom file. I will look into it when I have the time.

**Comment by ak-il** [comment]
I downloaded `org.apache.logging.log4j:log4j-core:2.13.0` (pass this to the script or use [this pom](https://pastebin.com/nBsr6X8Q) for your plugin) using both the script and the plugin.
With your plugin the output directory weighs around 17 MB where with my plugin the output weighs 225 MB.
Actually the pom also downloads junit. 
That's a big difference IMO so that makes me wonder why is that.
Is it the fact the the scripts attempts to download sources and javadocs for dependencies too?

**Comment by Theoderich** [comment]
I have played around with your script and my plugin.

First and foremost: I have identified a bug in the go-offline-maven-plugin that prevented it from downloading any plugins if there is an error downloading dependencies. Since the junit:junit:3.8.1 dependency does not have a javadoc deployed, this bug was triggered. I have already fixed it in the current SNAPSHOT build. So thank you for that! :)

Without this bug, I get a difference of 41MB (plugin) vs. 83MB (script). Looking through the repos the repository generated by the plugin almost perfectly matches the output of simply doing a "mvn clean deploy site" on the provided pom file. Of course the plugin downloads sources and javadocs, which the build does not.
The script downloads a lot more dependencies including springframework-core and groovy. Why the script does this is beyond me. The maven-dependency-plugin does behave oddly in many ways (which is part of the reason I wrote the go-offline-plugin)

**Comment by ak-il** [comment]
I'm glad about fixing the bug!
Well maybe we will be fortunate enough one day to find out :)
Thanks for replying.

**Comment by pschichtel** [comment]
Maven's dependency plugin in version 3.1.2 now also seems to correctly handle reactor projects. Is there still a benefit in using this plugin over the dependency plugin? (sorry for kind-of hijacking this issue, but I think this is related)

**Comment by Theoderich** [comment]
So they finally fixed it? I'll have to take a look and compare the outputs of both plugins. Maybe the go-offline plugin is indeed obsolete now.

**Comment by Theoderich** [comment]
Unfortunately, I almost instantly found another bug in dependency:go-offline: Repositories are not resolved correctly from parent poms.
[](https://issues.apache.org/jira/browse/MDEP-680)
So in my view, dependency:go-offline is still no alternative to the go-offline-maven-plugin ;)

**Comment by pschichtel** [comment]
The project I need to this for luckily doesn't have custom repositories. We just have a global mirror configured, which works as usual.

But just to clarify: Given dependency:go-offline would work as expected, there would be no need for this plugin, right?

**Comment by Theoderich** [comment]
Yeah if dependency:go-offline would work as expected this plugin would be obsolete. I did start developing it because of the bugs in dependency:go-offline after all ;)

The plugin still has some features that dependency:go-offline lacks (DynamicDependencies and automatic sources/jacadoc download). But those could be added to dependency:go-offline as well.

**Comment by busbey** [comment]
FYI dependency:go-offline also behaves incorrectly if you have a reactor project where one module has a non-test dependency on another module's test artifact.

**Comment by Theoderich** [comment]
> FYI dependency:go-offline also behaves incorrectly if you have a reactor project where one module has a non-test dependency on another module's test artifact.

Can you elaborate?

**Comment by busbey** [comment]
my attempt to make a reproduction project shows intra-module test dependencies working. let me see if I can figure out why the more complex project fails.

**Comment by busbey** [comment]
I have managed to work through a reproduction now, and it is not that the dependency-plugin fails at a reactor dependency at all. the issue looks to be something like [MDEP-507](https://issues.apache.org/jira/browse/MDEP-507) where it ignores plugin dependencies specified in the project pom.

**Comment by hcguersoy** [comment]
@busbey I can confirm this, running into the same issue yesterday, driving me nuts.

**Comment by Theoderich** [comment]
> I have managed to work through a reproduction now, and it is not that the dependency-plugin fails at a reactor dependency at all. the issue looks to be something like [MDEP-507](https://issues.apache.org/jira/browse/MDEP-507) where it ignores plugin dependencies specified in the project pom.

So the reproducer from MDEP-507 also causes the bug in the go-offline-plugin correct? I will look into this as soon as possible

**Comment by Theoderich** [comment]
I tried to reproduce the problem described in MDEP-507, but the go-offline plugin does download the correct versions. See the pom.xml I used below.
@busbey can you provide a pom.xml that reproduces the problem?

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.qaware.maven</groupId>
    <artifactId>plugin-dependency-reproducer</artifactId>
    <version>1.0-SNAPSHOT</version>


    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>selenium-maven-plugin</artifactId>
                <version>2.3</version>
                <dependencies>
                    <dependency>
                        <groupId>org.seleniumhq.selenium</groupId>
                        <artifactId>selenium-server</artifactId>
                        <version>2.47.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.seleniumhq.selenium</groupId>
                        <artifactId>selenium-remote-driver</artifactId>
                        <version>2.47.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.seleniumhq.selenium</groupId>
                        <artifactId>selenium-api</artifactId>
                        <version>2.47.1</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>`

**Comment by busbey** [comment]
oh go-offline-plugin definitely does the correct thing. I was providing an example of where go-offline-plugin is still very useful even after dependency-plugin:go-offline fixes MDEP-204 and MDEP-608. Sorry for the misunderstanding :)

**Comment by Theoderich** [comment]
Ah ^^ Thanks for clearing that up :D
