### ISSUE TITLE
Dynamic dependency not fetched

### ISSUE THREAD

**Issue by mustaphazorgati** [qaware/go-offline-maven-plugin#24]
Hey there!

I just tried out this plugin with this configuration
```
<plugin>
  <groupId>de.qaware.maven</groupId>
  <artifactId>go-offline-maven-plugin</artifactId>
  <version>1.2.8</version>
  <configuration>
    <dynamicDependencies>
      <DynamicDependency>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${version.maven.surefire}</version>
        <repositoryType>PLUGIN</repositoryType>
      </DynamicDependency>
    </dynamicDependencies>
  </configuration>
</plugin>
```
Unfortunately the maven-surefire-plugin's dynamic dependencies are not fetched. 
Is this a bug or am I using a wrong configuration?

**Comment by mustaphazorgati** [comment]
@Theoderich can you please have a short look? :)

**Comment by Theoderich** [comment]
Hey, sorry for the delayed answer.
So the problem here is that the maven-surefire-plugin and some other plugins dynamically download additional dependencies during their runtime. Since these dynamic dependencies are hidden in the code of those plugins, there is no way for the go-offline-maven-plugin to know about them.

Thats what the dynamicDependencies section of the configuration is for: To manually tell the go-offline-plugin about those dependencies. Maybe I should have called the section "ManualDependencies".

So in your case, you have to add the dependencies that the surefire-plugin downloads dynamically, not the surefire plugin itself.
For example, if you use junit-4 tests, the surefire-plugin dynamically downloads "org.apache.maven.surefire:surefire-junit4". In that case your dynamicDependencies section has to look like this:


```
<dynamicDependencies>
      <DynamicDependency>
        <groupId>org.apache.maven.surefire</groupId>
        <artifactId>surefire-junit4</artifactId>
        <version>${version.maven.surefire}</version>
        <repositoryType>PLUGIN</repositoryType>
      </DynamicDependency>
</dynamicDependencies>
```


Which specific dynamic dependencies you need can unfortionatly only be determined by analysing the downloads of a full mvn install after running the go-offline-plugin.

Hope that helps

**Comment by mustaphazorgati** [comment]
Hey @Theoderich! 
Thank you that detailed answer. I misunderstood `DynamicDependency` :)
