### ISSUE TITLE
Failed Jar dependencies

### ISSUE THREAD

**Issue by viktasidenfy** [qaware/go-offline-maven-plugin#26]
Hi, I'm having trouble in downloading all dependencies with `mvn -B de.qaware.maven:go-offline-maven-plugin:resolve-dependencies`. I've added google maven repository, which has only .aar files.  So when I try to resolve-dependencies, all pom files downloads successfully, but I get a warning that .jar files could not be found for the google dependencies, even though I can see that .aar files were downloaded successfully. Then on `mvn -B install -DskipTests`the build fails with the following error. How can I fix that?

`[ERROR] Failed to execute goal on project com.idenfy.idenfysdk.core: Could not resolve dependencies for project idenfy:com.idenfy.idenfysdk.core:aar:5.1.4: The following artifacts could not be resolved: androidx.appcompat:appcompat:jar:1.2.0, androidx.core:core:jar:1.3.1, androidx.cardview:cardview:jar:1.0.0, androidx.coordinatorlayout:coordinatorlayout:jar:1.1.0, androidx.annotation:annotation-experimental:jar:1.0.0, androidx.fragment:fragment:jar:1.0.0, androidx.lifecycle:lifecycle-runtime:jar:2.0.0, androidx.recyclerview:recyclerview:jar:1.0.0, androidx.transition:transition:jar:1.2.0, androidx.vectordrawable:vectordrawable:jar:1.1.0, androidx.viewpager2:viewpager2:jar:1.0.0, io.reactivex.rxjava2:rxandroid:jar:2.1.1: androidx.appcompat:appcompat:jar:1.2.0 was not found in https://maven.google.com/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of google-repo has elapsed or updates are forced -> [Help 1]
`

I'm attaching my pom.xml file

[pom.xml.txt](https://github.com/qaware/go-offline-maven-plugin/files/6965856/pom.xml.txt)

**Comment by Theoderich** [comment]
I don't think this is a problem related to the go-offline-plugin. Your pom.xml does not work even without using the go-offline-plugin.

The libraries published in the google maven repository do not seem to be standard conform. They depend on other aar packets but do not specify the type of the dependencies. Since the default is jar, maven tries to download .jar files which do not exist.

Since gradle is the default build system for android I suspect that google uses a plugin in gradle to make .aar packets the default. How to get it to work in maven I sadly do not know.

**Comment by viktasidenfy** [comment]
Yeah, it's unfortunate. But thanks for your input!
